; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

; A candidate equality is impossible if substituting its constant into the
; predecessor condition would take the other edge.
define i1 @domcond_doubled_value(i32 noundef %x) {
; CHECK-LABEL: define i1 @domcond_doubled_value(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[DOUBLE:%.*]] = shl i32 [[X]], 1
; CHECK-NEXT:    [[GUARD:%.*]] = icmp slt i32 [[DOUBLE]], [[X]]
; CHECK-NEXT:    br i1 [[GUARD]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %double = add i32 %x, %x
  %guard = icmp slt i32 %double, %x
  br i1 %guard, label %then, label %else

then:
  %is8 = icmp eq i32 %x, 8
  %is16 = icmp eq i32 %x, 16
  %result = or i1 %is8, %is16
  ret i1 %result

else:
  ret i1 false
}

define i1 @domcond_mask_false_edge(i64 noundef %x) {
; CHECK-LABEL: define i1 @domcond_mask_false_edge(
; CHECK-SAME: i64 noundef [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LOW:%.*]] = and i64 [[X]], 15
; CHECK-NEXT:    [[ALIGNED:%.*]] = icmp eq i64 [[LOW]], 0
; CHECK-NEXT:    br i1 [[ALIGNED]], label %[[ALIGNED_BB:.*]], label %[[UNALIGNED_BB:.*]]
; CHECK:       [[ALIGNED_BB]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[UNALIGNED_BB]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %low = and i64 %x, 15
  %aligned = icmp eq i64 %low, 0
  br i1 %aligned, label %aligned.bb, label %unaligned.bb

aligned.bb:
  ret i1 false

unaligned.bb:
  %is16 = icmp eq i64 %x, 16
  ret i1 %is16
}

define i1 @domcond_mask_false_edge_ne(i64 noundef %x) {
; CHECK-LABEL: define i1 @domcond_mask_false_edge_ne(
; CHECK-SAME: i64 noundef [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LOW:%.*]] = and i64 [[X]], 15
; CHECK-NEXT:    [[ALIGNED:%.*]] = icmp eq i64 [[LOW]], 0
; CHECK-NEXT:    br i1 [[ALIGNED]], label %[[ALIGNED_BB:.*]], label %[[UNALIGNED_BB:.*]]
; CHECK:       [[ALIGNED_BB]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[UNALIGNED_BB]]:
; CHECK-NEXT:    ret i1 true
;
entry:
  %low = and i64 %x, 15
  %aligned = icmp eq i64 %low, 0
  br i1 %aligned, label %aligned.bb, label %unaligned.bb

aligned.bb:
  ret i1 false

unaligned.bb:
  %not16 = icmp ne i64 %x, 16
  ret i1 %not16
}

; On the other edge, x == 16 is possible and must not be folded away.
define i1 @domcond_mask_true_edge(i64 noundef %x) {
; CHECK-LABEL: define i1 @domcond_mask_true_edge(
; CHECK-SAME: i64 noundef [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LOW:%.*]] = and i64 [[X]], 15
; CHECK-NEXT:    [[ALIGNED:%.*]] = icmp eq i64 [[LOW]], 0
; CHECK-NEXT:    br i1 [[ALIGNED]], label %[[ALIGNED_BB:.*]], label %[[UNALIGNED_BB:.*]]
; CHECK:       [[ALIGNED_BB]]:
; CHECK-NEXT:    [[IS16:%.*]] = icmp eq i64 [[X]], 16
; CHECK-NEXT:    ret i1 [[IS16]]
; CHECK:       [[UNALIGNED_BB]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %low = and i64 %x, 15
  %aligned = icmp eq i64 %low, 0
  br i1 %aligned, label %aligned.bb, label %unaligned.bb

aligned.bb:
  %is16 = icmp eq i64 %x, 16
  ret i1 %is16

unaligned.bb:
  ret i1 false
}
